[xml]
substitution_model = """
<substModel id="binaryCTMC" spec="GeneralSubstitutionModel">
    <parameter dimension="2" estimate="false" id="rates.binaryCTMC" name="rates">1.0 1.0</parameter>
    <frequencies id="freqs" spec="Frequencies" frequencies="0.7 0.3"/>
</substModel>
"""

logs = """
"""

operators = """
"""

parameters = """ """

priors = """
"""

[defaults]
freqParameter = 0.5
