[xml]
clock_model = """
<branchRateModel id="clock" spec="beast.evolution.branchratemodel.UCRelaxedClockModel" rates="@branchRates" tree="@acg" clock.rate="@clockRate">
    <LogNormal id="logNormal:ucldStdev:clock" meanInRealSpace="true" name="distr" M="1.0" S="@ucldStdev:clock" />
</branchRateModel>
"""

parameters = """
        <stateNode id="clockRate" spec="RealParameter" lower="0.0">0.5</stateNode>
        <stateNode id="ucldStdev:clock" spec="RealParameter" estimate="false" lower="0.0" upper="3.0" value="{{clock_stdev}}"/>
        <stateNode id="branchRates" spec="RealParameter" lower="0.0">0.5</stateNode>
"""

priors = """
        <prior id="branchRatesPrior" name="distribution" x="@branchRates">
            <LogNormal id="LogNormal:branchRatesPrior" S="@ucldStdev:clock" M="1.0" meanInRealSpace="true" name="distr"/>
        </prior>
"""

_priors = """

"""

operators = """
    <operator id="branchRatesRandomWalk" spec="RealRandomWalkOperator" parameter="@branchRates" windowSize="0.2" weight="5.0"/>
    <operator id="branchRatesScaleOperator" spec="ScaleOperator" parameter="@branchRates" scaleFactor="0.6" weight="8.0"/>
    <operator id="RatesSwapOperator" spec="SwapOperator" parameter="@branchRates" weight="2.0"/>
"""

_operators = """
    <operator id="ucldStdevScaler.c:clock" spec="ScaleOperator" parameter="@ucldStdev:clock" scaleFactor="0.5" weight="2.0"/>
    <operator id="branchRatesUcldStdevScaler" spec="consoperators.UcldScalerOperator"
          rates="@branchRates" stdev="@ucldStdev:clock" distr="@logNormal:ucldStdev:clock" scaleFactor="0.5" weight="3.0"/>
"""


logs = """
        <log idref="clockRate"/>
        <log idref="ucldStdev:clock"/>
        <log idref="branchRates"/>

        <log id="groundTruth.branchRates" spec="RealParameter" value="{{branchRates}}"/>
"""

_logs = """
        <log branchratemodel="@clock" spec="beast.evolution.branchratemodel.RateStatistic" tree="@acg"/>
"""

[defaults]
clockRate = 1.0
clock_stdev = 0.3