[xml]
population_model = """
        <distribution id="networkPrior" spec="contactrees.model.ACGDistribution" network="@acg" conversionRate="@conversionRate" linearContactGrowth="true" upperConvCountBound="20">
            <cfModel id="YuleModel" spec="beast.evolution.speciation.YuleModel" tree="@acg" birthDiffRate="@birthRate" conditionalOnRoot="false"/>
        </distribution>
        <distribution id="ConvMovePrior.t:treeSim" spec="ConversionMovePrior" network="@acg" blockSet="@allBlocks" pMove="@pMove"/>
"""

logs = """
        <log idref="birthRate"/>
        <log spec="ACGStatsLogger" network="@acg" blockSet="@allBlocks"/>
        <log idref="conversionRate"/>
        <log idref="expectedConversions"/>
        <log idref="pMove"/>
"""

operators = """
    <operator id="ACGscale.updown.t" spec="ACGScaler" acg="@acg" scaleFactor="0.7" weight="8.0">
        <parameterInverse idref="clockRate"/>
    </operator>
    <operator id="ACGscale.t" spec="ACGScaler" acg="@acg" scaleFactor="0.9" weight="1.0"/>
    <operator id="ACGscale.rootOnly.t" spec="ACGScaler" acg="@acg" scaleFactor="0.9" weight="1.0" rootOnly="true"/>

    <operator id="CFWilsonBalding.t" spec="CFWilsonBalding" acg="@acg" conversionRate="@conversionRate" pMove="@pMove" blockSet="@allBlocks" includeRoot="false" alpha="0.1" networkPrior="@networkPrior" weight="3.0"/>
    <operator id="CFUniform.t" spec="CFUniform" acg="@acg" conversionRate="@conversionRate" pMove="@pMove" blockSet="@allBlocks" networkPrior="@networkPrior" weight="20.0"/>
    <operator id="CFNarrowExchange.t" spec="CFSubtreeExchange" acg="@acg" conversionRate="@conversionRate" pMove="@pMove" blockSet="@allBlocks" isNarrow="true" networkPrior="@networkPrior" weight="7.0"/>      
    <operator id="CFWideExchange.t" spec="CFSubtreeExchange" acg="@acg" conversionRate="@conversionRate" pMove="@pMove" blockSet="@allBlocks" isNarrow="false" networkPrior="@networkPrior" weight="3.0"/>

    <operator id="AddRemoveConversion.t" spec="AddRemoveConversionGibbs" weight="40.0" acg="@acg" pMove="@pMove" conversionRate="@conversionRate" blockSet="@allBlocks" networkPrior="@networkPrior">
        <plate var="x" range="&blockrange;">
            <treeLikelihood idref="treeLikelihood.block$(x)"/>
        </plate>
    </operator>
    <operator id="GibbsSampleMovesPerConversion.t" spec="GibbsSampleMovesPerConversion" weight="20.0" acg="@acg" pMove="@pMove" blockSet="@allBlocks">
        <plate var="x" range="&blockrange;">
            <treeLikelihood idref="treeLikelihood.block$(x)"/>
        </plate>
    </operator>
    <operator id="ConvertedEdgeSlide.t" spec="ConvertedEdgeSlide" acg="@acg" weight="12.0"/>
    <operator id="ConvertedEdgeHop.narrow" spec="ConvertedEdgeHopGibbs" acg="@acg" blockSet="@allBlocks" nClosestRelatives="3" pMove="@pMove" conversionRate="@conversionRate" networkPrior="@networkPrior" weight="7.0">
        <plate var="x" range="&blockrange;">
          <treeLikelihood idref="treeLikelihood.block$(x)"/>
        </plate>
    </operator>

    <operator id="CFConversionSwap.t" spec="CFConversionSwap" acg="@acg" conversionRate="@conversionRate" 
                  pMove="@pMove" blockSet="@allBlocks" networkPrior="@networkPrior" weight="4.0"/>

    <operator id="ExpectedConversionScaler" spec="ScaleOperator" parameter="@expectedConversions" scaleFactor="0.8" weight="5.0"/>
    <operator id="PMoveScaler" spec="ScaleOperator" parameter="@pMove" scaleFactor="0.6" weight="5.0"/>

"""

_operators = """
    <operator id="AddRemoveConversion.t" spec="AddRemoveConversion" weight="20.0" acg="@acg" pMove="@pMove" conversionRate="@conversionRate" blockSet="@allBlocks" networkPrior="@networkPrior"/>

    <operator id="ConvertedEdgeFlip.t" spec="ConvertedEdgeFlip" acg="@acg" weight="5.0"/>
    <operator id="ConversionSplit.t" spec="ConversionSplit" acg="@acg" weight="3.0" 
              blockSet="@allBlocks" conversionRate="@conversionRate" flip="false" pMove="@pMove"/>
    <operator id="ConversionSplitAndFlip.t" spec="ConversionSplit" acg="@acg" weight="3.0" 
              blockSet="@allBlocks" conversionRate="@conversionRate" flip="true" pMove="@pMove"/>

    <operator id="BirthRateScaler" spec="ScaleOperator" parameter="@birthRate" scaleFactor="0.7" weight="3.0"/>

    <operator id="ConversionRateScaler" spec="ScaleOperator" parameter="@conversionRate" scaleFactor="0.6" weight="5.0"/>
"""

parameters = """
        <stateNode id="birthRate" spec="RealParameter" estimate="false" value="{{birthRate}}"/>
        <stateNode id="pMove" spec="RealParameter" estimate="true" value="{{pMove}}" lower="0.01" upper="0.35"/>
        <stateNode id="expectedConversions" spec="RealParameter" estimate="true" value="{{expectedConversions}}" lower="0.0" upper="20.0"/>
        <stateNode id="conversionRate" spec="ConversionRate" expectedConversions="@expectedConversions" network="@acg" linearContactGrowth="true" />
"""
_parameters = """
        <stateNode id="conversionRate" spec="RealParameter" estimate="true" value="{{conversionRate}}"/>
"""

priors = """
            <prior id="pMovePrior" name="distribution" x="@pMove">
                <Beta id="Beta.pMove" name="distr" alpha="6.0" beta="36.0"/>
            </prior>
            <prior id="expectedConversionsPrior" name="distribution" x="@expectedConversions">
                <distr id="distr.expectedConversionsPrior" spec="beast.math.distributions.Gamma" alpha="10.0" beta="0.4" />
            </prior>
"""
_priors = """
            <prior id="birthRatePrior" name="distribution" x="@birthRate">
                <Gamma id="Gamma.birthRate" mode="ShapeScale" name="distr" alpha="30.0" beta="0.1"/>
            </prior>
"""

[defaults]
birthRate = 2.0
pMove = 0.15
conversionRate = 1.0
expectedConversions = 4.0
