[xml]

[templates]
alignment = "alignment.toml"
substitution_model = "subst_models/ctmc.toml"
population_model = "network_models/Tree_Yule.toml"
clock_model = "clock_models/strict.toml"

[defaults]
chain_length = 1000000
log_every =  1000
sample_from_prior = false
seqlength = 10
