[xml]

[templates]
alignment = "alignment.toml"
substitution_model = "subst_models/ctmc.toml"
population_model = "network_models/ACG_Yule_fixedRate.toml"
clock_model = "clock_models/relaxed_lognormal_fixedRate.toml"

[defaults]
chain_length = 20000
log_every = 100
sample_from_prior = false
seqlength = 20
