[xml]
alignment = """
    <data id="simulated.block.$(x)" dataType="{{datatype}}">
        {{#taxa}}
        <sequence taxon="{{.}}">?</sequence>
        {{/taxa}}
    </data>
"""


[defaults]
datatype = "binary"
