[xml]

[templates]
alignment = "alignment.toml"
substitution_model = "subst_models/ctmc.toml"
population_model = "network_models/ACGyule.toml"
clock_model = "clock_models/relaxed_lognormal.toml"

[defaults]
chain_length = 10000000
log_every = 4000
sample_from_prior = false
seqlength = 30
