[xml]

[templates]
alignment = "alignment.toml"
substitution_model = "subst_models/ctmc.toml"
population_model = "network_models/ACGyule.toml"
clock_model = "clock_models/strict.toml"

[defaults]
chain_length = 15000000
log_every = 3000
sample_from_prior = false
seqlength = 20
