[xml]
substitution_model = """
<substModel id="binaryCTMC" spec="GeneralSubstitutionModel">
    <parameter id="rates.binaryCTMC" dimension="2" name="rates">1.0 1.0</parameter>
    <frequencies id="freqs" spec="Frequencies" frequencies="0.5 0.5"/>
</substModel>
"""

logs = """
"""

operators = """
"""

parameters = """ """

priors = """
"""

[defaults]
